// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5nv465HhaxMb6QUsBteICgM-ATBOVkyU',
    appId: '1:301656407387:web:3152e79a66489cf26fee7e',
    messagingSenderId: '301656407387',
    projectId: 'rewire-52790',
    authDomain: 'rewire-52790.firebaseapp.com',
    storageBucket: 'rewire-52790.firebasestorage.app',
    measurementId: 'G-LQRDZDX86G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh3Kf4m-PUCs42zIWec7zgI4WFYyKm35o',
    appId: '1:301656407387:android:6c62d6925b21c4486fee7e',
    messagingSenderId: '301656407387',
    projectId: 'rewire-52790',
    storageBucket: 'rewire-52790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKdwi5TfHq5pWKZkWuHzoMa9Ek7aop1Gc',
    appId: '1:301656407387:ios:8df83bc3a056ef7d6fee7e',
    messagingSenderId: '301656407387',
    projectId: 'rewire-52790',
    storageBucket: 'rewire-52790.firebasestorage.app',
    androidClientId: '301656407387-l3bft26q3f1duluke8upof007bt8q76g.apps.googleusercontent.com',
    iosClientId: '301656407387-80nqeinmphljj838c6fo1ek477vddju6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rewireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKdwi5TfHq5pWKZkWuHzoMa9Ek7aop1Gc',
    appId: '1:301656407387:ios:8df83bc3a056ef7d6fee7e',
    messagingSenderId: '301656407387',
    projectId: 'rewire-52790',
    storageBucket: 'rewire-52790.firebasestorage.app',
    androidClientId: '301656407387-l3bft26q3f1duluke8upof007bt8q76g.apps.googleusercontent.com',
    iosClientId: '301656407387-80nqeinmphljj838c6fo1ek477vddju6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rewireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5nv465HhaxMb6QUsBteICgM-ATBOVkyU',
    appId: '1:301656407387:web:d71eb00e4a431ac06fee7e',
    messagingSenderId: '301656407387',
    projectId: 'rewire-52790',
    authDomain: 'rewire-52790.firebaseapp.com',
    storageBucket: 'rewire-52790.firebasestorage.app',
    measurementId: 'G-0ZC4MPJH8X',
  );
}
